version: '3.7'

networks:
  net:
    external: true
    driver: bridge

services:
  frontend:
    container_name: frontend
    restart: always
    build: 
      context: ./frontend
    ports:
      - 5173:5173
    networks:
      - net

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
    ports:
      - 3323:3323
    volumes:
      - ./backend:/usr/src/app:cached
    networks:
      - net

  nginx:
    container_name: nginx
    restart: always
    image: ubuntu/nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - net

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    networks:
      - net
